#%RAML 1.0
title: ITAR-TASS API
version: v1
description: ITAR-TASS API description RAML templates
types:
  AuthorAttributes:
    type: object
    properties:
      id:
        required: true
        type: integer
      name:
        required: false
        type: string
        minLength: 16
        maxLength: 128
  Author:
    type: object
    properties:
      type:
        required: true
        type: string
      id:
        required: true
        type: integer
      attributes: AuthorAttributes
  CommentAttributes:
    type: object
    properties:
      id:
        required: true
        type: integer
      text:
        required: true
        type: string
        minLength: 32
        maxLength: 256
      time:
        required: true
        type: datetime
  Comment:
    type: object
    properties:
      type:
        required: true
        type: string
      id:
        required: true
        type: integer
      attributes: CommentAttributes
      relationships: Author
  ArticleAttributes:
    type: object
    properties:
      id:
        required: true
        type: integer
      title:
        required: true
        type: string
        minLength: 8
        maxLength: 128
      description:
        required: true
        type: string
        minLength: 64
        maxLength: 4096
      time:
        required: true
        type: date-only
  Article:
    type: object
    properties:
      type:
        required: true
        type: string
      id:
        required: true
        type: integer
      attributes: ArticleAttributes
      relationships: Author[] | Comment[]
/articles/:
  get:
    responses:
      200:
        body:
          application/json.vnd+json:
            type: Article[]
  post:
    body:
     application/json.vnd+json:
      type: Article
  patch:
    body:
     application/json.vnd+json:
      type: Article
  delete:
    body:
     application/json.vnd+json:
      type: Article[]
/articles/{id}:
  get:
    responses:
      200:
        body:
          application/json.vnd+json:
            type: Article
