#%RAML 1.0
title: ITAR-TASS API
version: v1
description: ITAR-TASS API description RAML templates
types:
  ID:
    type: integer
    required: true
  Type:
    type: string
    required: true
    minLength: 1
    maxLength: 255
  Data:
    type: object
    required: true
  # Relationships:
  #   type: object
  #   properties:
  #     id:
  #       type: ID
  #     type:
  #       type: Type
  # SingleDataRelationships:
  #   type: object
  #   properties:
  #     data:
  #       type: Relationships
  # MultipleDataRelationships:
  #   type: object
  #   properties:
  #     data:
  #       type: Relationships[]
  #       uniqueItems: true
  AuthorRelationships:
    type: object
    properties:
      data:
        type: Data
        properties:
         id: ID
         type: Type
  AuthorAttributes:
    type: object
    properties:
      name:
        required: false
        type: string
        minLength: 16
        maxLength: 128
  Author:
    type: object
    properties:
      type: Type
      id: ID
      attributes: AuthorAttributes
  CommentRelationships:
    type: object
    properties:
      data:
        type: Data
        properties:
          id: ID
          type: Type
          relationships: AuthorRelationships
  CommentAttributes:
    type: object
    properties:
      text:
        required: true
        type: string
        minLength: 32
        maxLength: 256
      time:
        required: true
        type: datetime
  Comment:
    type: object
    properties:
      type: Type
      id: ID
      attributes: CommentAttributes
      relationships: AuthorRelationships
  ArticleRelationships:
    type: object
    properties:
      data:
        type: Data
        properties:
          id: ID
          type: Type
          relationships: AuthorRelationships | CommentRelationships
  ArticleAttributes:
    type: object
    properties:
      title:
        required: true
        type: string
        minLength: 8
        maxLength: 128
      description:
        required: true
        type: string
        minLength: 64
        maxLength: 4096
      time:
        required: true
        type: date-only
  Article:
    type: object
    properties:
      type: Type
      id: ID
      attributes: ArticleAttributes
      relationships: AuthorRelationships | CommentRelationships
/articles:
  get:
    responses:
      200:
        body:
          application/json.vnd+json:
            type: Article[]
  post:
    body:
     application/json.vnd+json:
      type: Article
  /{id}:
    get:
      responses:
        200:
          body:
            application/json.vnd+json:
              type: Article
    patch:
      body:
       application/json.vnd+json:
        type: Article
    delete:
      responses:
        204:
    /relationships/{relation}:
      get:
        responses:
          200:
            body:
              application/json.vnd+json:
                type: AuthorRelationships | CommentRelationships
      post:
        body:
         application/json.vnd+json:
          type: AuthorRelationships | CommentRelationships
      patch:
        body:
         application/json.vnd+json:
          type: AuthorRelationships | CommentRelationships
      delete:
        responses:
          204:
    /{relation}:
      get:
        responses:
          200:
            body:
              application/json.vnd+json:
                type: Author | Comment[]
