#%RAML 1.0
title: Task
description: Система Планирования
baseUri: http://api.tass.ru/{version}
version: v1

/task:
  get:
    displayName: getTasks
    queryParameters:
      page:
        type: integer
        default: 1
        description: Номер страницы
      per_page:
        type: integer
        default: 15
        description: Количество записей на странице
      order_by:
        type: string
        required: false
        description: Поля, по которому выполняется сортировка
      order_dir:
        type: string
        required: false
        enum: [DESC, ASC]
        default: ASC
        description: Тип сортировки
    responses:
      200:
        body:
          application/json.vnd+json:
            type: array
            items:
              type: Task
  /{id}:
    get:
      displayName: getTask
      responses:
        200:
          body:
            application/json.vnd+json:
              type: Task

types:
  FAKE:
    type: boolean
    default: true

  ID:
    type: integer
    required: true

  UserAttributes:
    type: object
    properties:
      title:
        type: string
        required: true
        description: Заголовок задания
      id: ID

  User:
    type: object
    properties:
      id: ID
      attributes: UserAttributes

  TagAttributes:
    type: object
    properties:
          title:
            type: string
            required: true
            description: Заголовок задания
          id: ID
  Tag:
    type: object
    properties:
      id: ID
      attributes: TagAttributes

  EventAttributes:
    type: object
    properties:
      title:
        type: string
        required: true
        description: Заголовок задания
      id: ID
  Event:
    type: object
    properties:
      id: ID
      attributes: EventAttributes

  Task:
    type: object
    properties:
      id: ID
      attributes: TaskAttributes
  TaskAttributes:
    type: object
    properties:
      title:
        type: string
        required: true
        description: Заголовок задания
      description:
        type: string
        description: Описание задания
      source:
        type: string
        required: true
        description: |
          Источник выдачи задания, система, в которой было сформировано задание
      deadline:
        type: datetime
        required: true
        description: Срок выполнения задания
      priority:
        enum: [low, medium, high, highest]
        required: true
        default: low
        description: Приоритет задания
      comment:
        type: string
        description: Комментарий к заданию
      status:
        enum: [new, in_work, close]
        required: true
        default: new
        description: Статус задания
      assignee:
        type: User
      tags:
        type: array
        items:
          type: Tag
      event_id:
        type: Event
