#%RAML 1.0
title: система планирования
baseUri: http://s-planning-backend.dev1.tass.ru/{version}
version: v1
protocols:
  - HTTP
mediaType: application/vnd.api+json

/topic/?page[number]={page}&page[size]={perPage}&sort={orderBy}:
  get:
    displayName: getTopics
    queryParameters:
      page:
        type: integer
        required: true
        default: 1
        example: 1
        description: номер страницы
      perPage:
        type: integer
        required: true
        default: 15
        example: 15
        description: количество элементов на странице
      orderBy:
        type: string
        required: false
    responses:
      200:
        description: |
          200 Get Topics
        body:
          application/vnd.api+json:
            schema: |
              {
                "$schema":"http://json-schema.org/draft-03/schema#",
                "type": "object",
                "description": "Get list topics",
                "properties": {
                  "data": {
                    "type": "array",
                    "required": true,
                    "items": [
                      {
                      "type": {
                        "type":      "string",
                        "required":  true,
                        "minLength": 1,
                        "maxLength": 255
                      },
                      "id": {
                        "type": "integer",
                        "description": "уникальный ключ записи",
                        "required":  true,
                        "minLength": 1,
                        "maxLength": 255
                      },
                        "attributes": {
                          "type":       "object",
                          "properties": {
                            "title": {
                              "type": "string",
                              "description": "название"
                            },
                            "is_general": {
                              "type": "boolean"
                            },
                            "priority": {
                              "type": "integer",
                              "description": "атрибут для явного указания порядка топика при сортировки"
                            },
                            "status": {
                              "type": "string",
                              "enum": [
                                "active",
                                "inactive",
                                "finished"
                              ]
                            },
                            "event_actual_cnt": {
                              "type": "integer",
                              "description": "количество Событий связанных с данным Топиком в данный момент"
                            },
                            "event_target_cnt": {
                              "type": "integer",
                              "description": "целевое(запланированное) количество Событий связанных с данным Топиком"
                            },
                            "created_at": {
                              "type": "integer"
                            }
                          }
                        },
                        "relationships": {
                          "type": "object",
                          "properties": {
                            "tags":   {
                              "type":       "object",
                              "properties": {
                                "data": {
                                  "type":  "array",
                                  "items": [
                                    {
                                      "type":       "object",
                                      "properties": {
                                        "id":   {
                                          "type":      "integer",
                                          "required":  true,
                                          "minLength": 1,
                                          "maxLength": 255
                                        },
                                        "type": {
                                          "type":     "string",
                                          "pattern":  "/^tag$/",
                                          "required": true
                                        }
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            "linked_topics": {
                              "type":       "object",
                              "properties": {
                                "data": {
                                  "type":       "array",
                                  "description": "массив Топиков связанных с данным Топиком",
                                  "items": [{
                                    "type":       "object",
                                    "properties": {
                                      "id":   {
                                        "type":      "integer",
                                        "required":  true,
                                        "minLength": 1,
                                        "maxLength": 255
                                      },
                                      "type": {
                                        "type":     "string",
                                        "pattern":  "/^topic$/",
                                        "required": true
                                      }
                                    }
                                  }]
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  },
                  "included": {
                    "type":     "array",
                    "required": false,
                    "items":    [
                      {
                        "type":          {
                          "type":      "string",
                          "required":  true,
                          "minLength": 1,
                          "maxLength": 255
                        },
                        "id":            {
                          "type":      "integer",
                          "required":  true,
                          "minLength": 1,
                          "maxLength": 255
                        },
                        "attributes":    {
                          "type":       "object",
                          "properties": {
                            "text": {
                              "type":     "string",
                              "required": true
                            }
                          }
                        },
                        "relationships": {
                          "type":       "object",
                          "properties": {
                            "tag": {
                              "type":  "array",
                              "items": [
                                {
                                  "type":       "object",
                                  "properties": {
                                    "id":   {
                                      "type":      "integer",
                                      "required":  true,
                                      "minLength": 1,
                                      "maxLength": 255
                                    },
                                    "type": {
                                      "type":      "string",
                                      "required":  true,
                                      "minLength": 1,
                                      "maxLength": 255
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        }
                      },
                      {
                        "type":          {
                          "type":      "string",
                          "required":  true,
                          "minLength": 1,
                          "maxLength": 255
                        },
                        "id":            {
                          "type":      "integer",
                          "required":  true,
                          "minLength": 1,
                          "maxLength": 255
                        },
                        "attributes":    {
                          "type":       "object",
                          "properties": {
                            "title": {
                              "type": "string",
                              "description": "название"
                            },
                            "is_general": {
                              "type": "boolean"
                            },
                            "priority": {
                              "type": "integer",
                              "description": "атрибут для явного указания порядка топика при сортировки"
                            },
                            "status": {
                              "type": "string",
                              "enum": [
                                "active",
                                "inactive",
                                "finished"
                              ]
                            },
                            "event_actual_cnt": {
                              "type": "integer",
                              "description": "количество Событий связанных с данным Топиком в данный момент"
                            },
                            "event_target_cnt": {
                              "type": "integer",
                              "description": "целевое(запланированное) количество Событий связанных с данным Топиком"
                            },
                            "created_at": {
                              "type": "integer"
                            },
                            "updated_by":{
                              "type": "string",
                              "description": "название"
                              },
                            "task_cnt":{
                              "type": "integer"
                              }
                          }
                        },
                        "relationships": {
                          "type":       "object",
                          "properties": {
                            "tags":   {
                              "type":       "object",
                              "properties": {
                                "data": {
                                  "type":  "array",
                                  "items": [
                                    {
                                      "type":       "object",
                                      "properties": {
                                        "id":   {
                                          "type":      "integer",
                                          "required":  true,
                                          "minLength": 1,
                                          "maxLength": 255
                                        },
                                        "type": {
                                          "type":     "string",
                                          "pattern":  "/^tag$/",
                                          "required": true
                                        }
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            "linked_topics": {
                              "type":       "object",
                              "properties": {
                                "data": {
                                  "type":       "object",
                                  "properties": {
                                    "type":       "object",
                                    "properties": {
                                      "id":   {
                                        "type":      "integer",
                                        "required":  true,
                                        "minLength": 1,
                                        "maxLength": 255
                                      },
                                      "type": {
                                        "type":     "string",
                                        "pattern":  "/^rubric$/",
                                        "required": true
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                }
              }
            example: |
              [
                {
                  "data": {
                    "type":          "topik",
                    "id":13,
                    "attributes":    {
                    "weight": 10,
                    "title": Шахматы,
                    "is_general": false,
                    "priority": 10,
                    "status": "active",
                    "event_actual_cnt": 0,
                    "event_target_cnt": 0,
                    "created_at": ""
                    },
                    "relationships": {
                      "tags":   {
                        "data": [
                          {
                            "id":   1,
                            "type": "tag"
                          },
                          {
                            "id":   2,
                            "type": "tag"
                          }
                        ]
                      },
                      "linked_topics": {
                        "data": {
                          "id":   7,
                          "type": "topik"
                        }
                      }
                    }
                  }
                }
              ]
/topic/{id}:
  get:
        queryParameters:
          id:
            type: integer
            required: true
            description: номер страницы
        displayName: getTopics
        responses:
          200:
            description: |
              200 Get Topics
            body:
              application/vnd.api+json:
                schema: |
                  {
                    "$schema":"http://json-schema.org/draft-03/schema#",
                    "type": "object",
                    "description": "Get list topics",
                    "properties": {
                      "data": {
                        "type": "array",
                        "required": true,
                        "items": [
                          {
                          "type": {
                            "type":      "string",
                            "required":  true,
                            "minLength": 1,
                            "maxLength": 255
                          },
                          "id": {
                            "type": "integer",
                            "description": "уникальный ключ записи",
                            "required":  true,
                            "minLength": 1,
                            "maxLength": 255
                          },
                            "attributes": {
                              "type":       "object",
                              "properties": {
                                "title": {
                                  "type": "string",
                                  "description": "название"
                                },
                                "is_general": {
                                  "type": "boolean"
                                },
                                "priority": {
                                  "type": "integer",
                                  "description": "атрибут для явного указания порядка топика при сортировки"
                                },
                                "status": {
                                  "type": "string",
                                  "enum": [
                                    "active",
                                    "inactive",
                                    "finished"
                                  ]
                                },
                                "event_actual_cnt": {
                                  "type": "integer",
                                  "description": "количество Событий связанных с данным Топиком в данный момент"
                                },
                                "event_target_cnt": {
                                  "type": "integer",
                                  "description": "целевое(запланированное) количество Событий связанных с данным Топиком"
                                },
                                "created_at": {
                                  "type": "integer"
                                }
                              }
                            },
                            "relationships": {
                              "type": "object",
                              "properties": {
                                "tags":   {
                                  "type":       "object",
                                  "properties": {
                                    "data": {
                                      "type":  "array",
                                      "items": [
                                        {
                                          "type":       "object",
                                          "properties": {
                                            "id":   {
                                              "type":      "integer",
                                              "required":  true,
                                              "minLength": 1,
                                              "maxLength": 255
                                            },
                                            "type": {
                                              "type":     "string",
                                              "pattern":  "/^tag$/",
                                              "required": true
                                            }
                                          }
                                        }
                                      ]
                                    }
                                  }
                                },
                                "linked_topics": {
                                  "type":       "object",
                                  "properties": {
                                    "data": {
                                      "type":       "array",
                                      "description": "массив Топиков связанных с данным Топиком",
                                      "items": [{
                                        "type":       "object",
                                        "properties": {
                                          "id":   {
                                            "type":      "integer",
                                            "required":  true,
                                            "minLength": 1,
                                            "maxLength": 255
                                          },
                                          "type": {
                                            "type":     "string",
                                            "pattern":  "/^topic$/",
                                            "required": true
                                          }
                                        }
                                      }]
                                    }
                                  }
                                }
                              }
                            }
                          }
                        ]
                      },
                      "included": {
                        "type":     "array",
                        "required": false,
                        "items":    [
                          {
                            "type":          {
                              "type":      "string",
                              "required":  true,
                              "minLength": 1,
                              "maxLength": 255
                            },
                            "id":            {
                              "type":      "integer",
                              "required":  true,
                              "minLength": 1,
                              "maxLength": 255
                            },
                            "attributes":    {
                              "type":       "object",
                              "properties": {
                                "text": {
                                  "type":     "string",
                                  "required": true
                                }
                              }
                            },
                            "relationships": {
                              "type":       "object",
                              "properties": {
                                "tag": {
                                  "type":  "array",
                                  "items": [
                                    {
                                      "type":       "object",
                                      "properties": {
                                        "id":   {
                                          "type":      "integer",
                                          "required":  true,
                                          "minLength": 1,
                                          "maxLength": 255
                                        },
                                        "type": {
                                          "type":      "string",
                                          "required":  true,
                                          "minLength": 1,
                                          "maxLength": 255
                                        }
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          },
                          {
                            "type":          {
                              "type":      "string",
                              "required":  true,
                              "minLength": 1,
                              "maxLength": 255
                            },
                            "id":            {
                              "type":      "integer",
                              "required":  true,
                              "minLength": 1,
                              "maxLength": 255
                            },
                            "attributes":    {
                              "type":       "object",
                              "properties": {
                                "title": {
                                  "type": "string",
                                  "description": "название"
                                },
                                "is_general": {
                                  "type": "boolean"
                                },
                                "priority": {
                                  "type": "integer",
                                  "description": "атрибут для явного указания порядка топика при сортировки"
                                },
                                "status": {
                                  "type": "string",
                                  "enum": [
                                    "active",
                                    "inactive",
                                    "finished"
                                  ]
                                },
                                "event_actual_cnt": {
                                  "type": "integer",
                                  "description": "количество Событий связанных с данным Топиком в данный момент"
                                },
                                "event_target_cnt": {
                                  "type": "integer",
                                  "description": "целевое(запланированное) количество Событий связанных с данным Топиком"
                                },
                                "created_at": {
                                  "type": "integer"
                                },
                                "updated_by":{
                                  "type": "string",
                                  "description": "название"
                                  },
                                "task_cnt":{
                                  "type": "integer"
                                  }
                              }
                            },
                            "relationships": {
                              "type":       "object",
                              "properties": {
                                "tags":   {
                                  "type":       "object",
                                  "properties": {
                                    "data": {
                                      "type":  "array",
                                      "items": [
                                        {
                                          "type":       "object",
                                          "properties": {
                                            "id":   {
                                              "type":      "integer",
                                              "required":  true,
                                              "minLength": 1,
                                              "maxLength": 255
                                            },
                                            "type": {
                                              "type":     "string",
                                              "pattern":  "/^tag$/",
                                              "required": true
                                            }
                                          }
                                        }
                                      ]
                                    }
                                  }
                                },
                                "linked_topics": {
                                  "type":       "object",
                                  "properties": {
                                    "data": {
                                      "type":       "object",
                                      "properties": {
                                        "type":       "object",
                                        "properties": {
                                          "id":   {
                                            "type":      "integer",
                                            "required":  true,
                                            "minLength": 1,
                                            "maxLength": 255
                                          },
                                          "type": {
                                            "type":     "string",
                                            "pattern":  "/^rubric$/",
                                            "required": true
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                example: |
                    {
                      "data": {
                        "type":          "topik",
                        "id":13,
                        "attributes":    {
                        "weight": 10,
                        "title": Шахматы,
                        "is_general": false,
                        "priority": 10,
                        "status": "active",
                        "event_actual_cnt": 0,
                        "event_target_cnt": 0,
                        "created_at": ""
                        },
                        "relationships": {
                          "tags":   {
                            "data": [
                              {
                                "id":   1,
                                "type": "tag"
                              },
                              {
                                "id":   2,
                                "type": "tag"
                              }
                            ]
                          },
                          "linked_topics": {
                            "data": {
                              "id":   7,
                              "type": "topik"
                            }
                          }
                        }
                      }
                    }
