<?php

namespace rjapitest\unit\extensions;

use Faker\Factory;
use Illuminate\Routing\Route;
use Illuminate\Http\Request;
use Modules\V2\Http\Controllers\ArticleController;
use rjapi\extension\BaseController;
use rjapi\extension\JSONApiInterface;
use rjapitest\_data\ArticleFixture;
use rjapitest\unit\TestCase;

/**
 * This method is used not only here, but in constructor of BaseController
 * to retrieve headers etc
 *
 * @param array $json
 * @return Request
 */
function request(array $json = [])
{
    $req = new Request();
    $req->headers->set('Content-TYpe', 'application/json;ext=bulk');
    $req->initialize([], [], [], [], [], [], json_encode($json));

    return $req;
}

/**
 * Class ApiController
 * @package rjapitest\unit\extensions
 *
 * @property BaseController baseController
 */
class ApiController extends TestCase
{
    private $baseController;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $_SERVER['HTTP_HOST'] = 'localhost';

        $router               = new Route(['POST', 'GET'], '', function () {
        });
        $this->baseController = new ArticleController($router);
    }

    /**
     * @test
     * @throws \rjapi\exceptions\HeadersException
     * @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
     * @throws \rjapi\exceptions\AttributesException
     */
    public function it_runs_index()
    {
        $router = new Route(['GET'], '/' . self::API_VERSION . '/article?include=tag&data=["title", "description"]', function () {
        });
        $router->setAction(['controller' => 'ArticleController@index']);
        $this->baseController = new ArticleController($router);

        $req = new Request();
        $req->initialize([
            'include' => 'tag',
        ]);
        $resp = $this->baseController->index($req);

        // @todo: Change simple 200 OK check to more complex tests
        $this->assertEquals($resp->getStatusCode(), JSONApiInterface::HTTP_RESPONSE_CODE_OK);
    }

    /**
     * @test
     * @throws \rjapi\exceptions\HeadersException
     * @throws AttributesException
     * @throws \rjapi\exceptions\AttributesException
     */
    public function it_runs_view()
    {
        $item = ArticleFixture::createAndGet();

        $router = new Route(['GET'], '/v2/article/' . $item->id . '?include=tag&data=["title", "description"]', function () {
        });
        $router->setAction(['controller' => 'ArticleController@view']);
        $this->assertTrue(is_string($item->id));

        $this->baseController = new ArticleController($router);

        $resp = $this->baseController->view(\rjapitest\unit\extensions\request(), $item->id);

        // @todo: Change simple 200 OK check to more complex tests
        $this->assertEquals($resp->getStatusCode(), JSONApiInterface::HTTP_RESPONSE_CODE_OK);
    }

    /**
     * @test
     * @throws \rjapi\exceptions\HeadersException
     * @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
     * @throws AttributesException
     * @throws \rjapi\exceptions\AttributesException
     */
    public function it_runs_create()
    {
        $router = new Route(['POST'], '/v2/article/', function () {
        });
        $router->setAction(['controller' => 'ArticleController@view']);

        $this->baseController = new ArticleController($router);

        $faker   = Factory::create();
        $reqData = [
            'data' => [
                'type'          => 'article',
                'attributes'    => [
                    'id'           => uniqid(),
                    'title'        => $faker->title,
                    'description'  => $faker->name,
                    'fake_attr'    => 'attr',
                    'url'          => 'http://example.com/articles_feed' . uniqid(),
                    'show_in_top'  => '0',
                    'topic_id'     => 1,
                    'rate'         => 5,
                    'date_posted'  => '2017-12-12',
                    'time_to_live' => '10:11:12',
                ],
                'relationships' => [
                    'topic' => [
                        'data' => ['type' => 'topic', 'id' => '2'],
                    ]
                ]
            ]
        ];


        $req = request($reqData);
        $resp = $this->baseController->create($req);

        $this->assertEquals($resp->getStatusCode(), JSONApiInterface::HTTP_RESPONSE_CODE_CREATED);

        $respData = json_decode($resp->getContent(), true);
        $this->assertEquals($reqData['data']['attributes']['id'], $respData['data']['id']);

        return $reqData;
    }

    /**
     * @test
     * @depends it_runs_create
     * @param array $reqData
     * @return array
     * @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
     * @throws \rjapi\exceptions\AttributesException
     */
    public function it_runs_update(array $reqData)
    {
        $faker   = Factory::create();
        $id = $reqData['data']['attributes']['id'];
        $reqData['data']['attributes']['title'] = $faker->title;

        $req = request($reqData);
        $resp = $this->baseController->update($req, $id);

        $this->assertEquals($resp->getStatusCode(), JSONApiInterface::HTTP_RESPONSE_CODE_OK);

        $respData = json_decode($resp->getContent(), true);
        $this->assertEquals($id, $respData['data']['id']);

        return $reqData;
    }

    /**
     * @test
     * @param array $reqData * @depends it_runs_update
     * @throws \SebastianBergmann\RecursionContext\InvalidArgumentException
     * @depends it_runs_update
     */
    public function it_runs_delete(array $reqData)
    {
        $id = $reqData['data']['attributes']['id'];

        $req = request($reqData);
        $resp = $this->baseController->delete($req, $id);

        $this->assertEquals($resp->getStatusCode(), JSONApiInterface::HTTP_RESPONSE_CODE_NO_CONTENT);
    }

    // @todo: relations/create|updateRelations/deleteRelations
}