<?php
use Illuminate\Routing\Controller;
use Illuminate\Routing\Route;
use Modules\V1\Http\Controllers\ArticleController;
use Modules\V1\Http\Controllers\DefaultController;
use rjapi\extension\BaseController;
use \Mockery as m;
use rjapi\extension\JSONApiInterface;

class BaseControllerTest extends TestCase
{
    private $route = null;
    private $obj = null;
    private $defaultController = null;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->route = new Route(['foo'], '/v1/bar', ['index']);
        $this->obj = new ArticleController($this->route);
    }

    public function testConstruction()
    {
        $this->assertInstanceOf(DefaultController::class, $this->obj);
        $this->assertInstanceOf(BaseController::class, $this->obj);
        $this->assertInstanceOf(Controller::class, $this->obj);
        $this->assertInstanceOf(JSONApiInterface::class, $this->obj);
    }

    public function testJsonApiIndex()
    {
        $request = new \Illuminate\Http\Request();
        $request->merge([
            'limit' => 10,
            'page' => 1,
            'data' => '["title", "description"]',
            'order_by' => '{"title":"asc", "created_at":"desc"}',
            'filter' => '[["updated_at", ">", "2017-01-03 12:13:13"], ["updated_at", "<", "2017-01-03 12:13:15"]]',
        ]);
        $this->obj->index($request);
    }
}